{
 "title": "netology Copyr",
 "time": { "from": "2026-01-28T21:05:03.401Z", "to": "2026-01-28T21:15:03.401Z" },
 "panels": [
  {
   "title": "количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5\r" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "количество места на файловой системе.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint!=\"/run\", mountpoint!~\"/run/.*\", fstype!=\"tmpfs\"} / 1e9\r"
    }
   ]
  },
  {
   "title": "утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\n\r\r"
    }
   ]
  }
 ]
}